INSERT INTO ALBUM (id, name, releaseDate) VALUES (1, '12 Bar Bruise', '07-09-2012')
INSERT INTO ALBUM (id, name, releaseDate) VALUES (2, 'Eyes Like the Sky', '22-02-2013')
INSERT INTO ALBUM (id, name, releaseDate) VALUES (3, 'Float Along - Fill Your Lungs', '27-09-2013')
INSERT INTO ALBUM (id, name, releaseDate) VALUES (4, 'Oddments', '07-03-2014')
INSERT INTO ALBUM (id, name, releaseDate) VALUES (5, 'I''m in Your Mind Fuzz', '31-10-2014)
INSERT INTO ALBUM (id, name, releaseDate) VALUES (6, 'Quarters!', '01-05-2015')
INSERT INTO ALBUM (id, name, releaseDate) VALUES (7, 'Paper Mâché Dream Balloon', '13-11-2015')
INSERT INTO ALBUM (id, name, releaseDate) VALUES (8, 'Nonagon Infinity', '29-04-2016')
INSERT INTO ALBUM (id, name, releaseDate) VALUES (9, 'Flying Microtonal Banana', '24-02-2017')
INSERT INTO ALBUM (id, name, releaseDate) VALUES (10, 'Murder of the Universe', '23-06-2017')
INSERT INTO ALBUM (id, name, releaseDate) VALUES (11, 'Sketches of Brunswick East', '18-08-2017')
INSERT INTO ALBUM (id, name, releaseDate) VALUES (12, 'Polygondwanaland', '17-11-2017')
INSERT INTO ALBUM (id, name, releaseDate) VALUES (13, 'Gumboot Soup', '31-12-2017')
INSERT INTO ALBUM (id, name, releaseDate) VALUES (14, 'Fishing For Fishies', '26-04-2019')


INSERT INTO SONG (id, name, albumID) VALUES (1, 'Robot Stop', 8)
INSERT INTO SONG (id, name, albumID) VALUES (2, 'Big Fig Wasp', 8)
INSERT INTO SONG (id, name, albumID) VALUES (3, 'Gamma Knife', 8)
INSERT INTO SONG (id, name, albumID) VALUES (4, 'People-Vultures', 8)
INSERT INTO SONG (id, name, albumID) VALUES (5, 'Mr. Beat', 8)
INSERT INTO SONG (id, name, albumID) VALUES (6, 'Evil Death Roll', 8)
INSERT INTO SONG (id, name, albumID) VALUES (7, 'Invisible Face', 8)
INSERT INTO SONG (id, name, albumID) VALUES (8, 'Wah Wah', 8)
INSERT INTO SONG (id, name, albumID) VALUES (9, 'Road Train', 8)

INSERT INTO SONG (id, name, albumID) VALUES (10, 'Sense', 7)
INSERT INTO SONG (id, name, albumID) VALUES (11, 'Bone', 7)
INSERT INTO SONG (id, name, albumID) VALUES (12, 'Dirt', 7)
INSERT INTO SONG (id, name, albumID) VALUES (13, 'Paper Mâché Dream Balloon', 7)
INSERT INTO SONG (id, name, albumID) VALUES (14, 'Trapdoor', 7)
INSERT INTO SONG (id, name, albumID) VALUES (15, 'Cold Cadaver', 7)
INSERT INTO SONG (id, name, albumID) VALUES (16, 'The Bitter Boogie', 7)
INSERT INTO SONG (id, name, albumID) VALUES (17, 'N.G.R.I. (Bloodstain)', 7)
INSERT INTO SONG (id, name, albumID) VALUES (18, 'Time = Fate', 7)
INSERT INTO SONG (id, name, albumID) VALUES (19, 'Time = $$$', 7)
INSERT INTO SONG (id, name, albumID) VALUES (20, 'Most of What I Like', 7)
INSERT INTO SONG (id, name, albumID) VALUES (21, 'Paper Mâché', 7)

INSERT INTO SONG (id, name, albumID) VALUES (22, 'Crumbling Castle', 12)
INSERT INTO SONG (id, name, albumID) VALUES (23, 'Polygondwanaland', 12)
INSERT INTO SONG (id, name, albumID) VALUES (24, 'The Castle In The Air', 12)
INSERT INTO SONG (id, name, albumID) VALUES (25, 'Deserted Dune Welcome Weary Feet', 12)
INSERT INTO SONG (id, name, albumID) VALUES (26, 'Inner Cell', 12)
INSERT INTO SONG (id, name, albumID) VALUES (27, 'Loyalty', 12)
INSERT INTO SONG (id, name, albumID) VALUES (28, 'Horology', 12)
INSERT INTO SONG (id, name, albumID) VALUES (29, 'Tetrachomacy', 12)
INSERT INTO SONG (id, name, albumID) VALUES (30, 'Searching...', 12)
INSERT INTO SONG (id, name, albumID) VALUES (31, 'The Fourth Colour', 12)

INSERT INTO SONG (id, name, albumID) VALUES (32, 'The River', 6)
INSERT INTO SONG (id, name, albumID) VALUES (33, 'Infinite Rise', 6)
INSERT INTO SONG (id, name, albumID) VALUES (34, 'God is in the Rhythm', 6)
INSERT INTO SONG (id, name, albumID) VALUES (35, 'Lonely Steel Sheet Flyer', 6)

INSERT INTO SONG (id, name, albumID) VALUES (36, 'Fishing For Fishies', 14)
INSERT INTO SONG (id, name, albumID) VALUES (37, 'Boogieman Sam', 14)
INSERT INTO SONG (id, name, albumID) VALUES (38, 'The Bird Song', 14)
INSERT INTO SONG (id, name, albumID) VALUES (39, 'Plastic Boogie', 14)
INSERT INTO SONG (id, name, albumID) VALUES (40, 'The Cruel Millennial', 14)
INSERT INTO SONG (id, name, albumID) VALUES (41, 'Real''s not real', 14)
INSERT INTO SONG (id, name, albumID) VALUES (42, 'This Thing', 14)
INSERT INTO SONG (id, name, albumID) VALUES (43, 'Acarine', 14)
INSERT INTO SONG (id, name, albumID) VALUES (44, 'Cyboogie', 14)

INSERT INTO SONG (id, name, albumID) VALUES (45, 'Rattlesnake', 9)
INSERT INTO SONG (id, name, albumID) VALUES (46, 'Melting', 9)
INSERT INTO SONG (id, name, albumID) VALUES (47, 'Open Water', 9)
INSERT INTO SONG (id, name, albumID) VALUES (48, 'Sleep Drifter', 9)
INSERT INTO SONG (id, name, albumID) VALUES (49, 'Billabong Valley', 9)
INSERT INTO SONG (id, name, albumID) VALUES (50, 'Anoxia', 9)
INSERT INTO SONG (id, name, albumID) VALUES (51, 'Doom City', 9)
INSERT INTO SONG (id, name, albumID) VALUES (52, 'Nuclear Fusion', 9)
INSERT INTO SONG (id, name, albumID) VALUES (53, 'Flying Microtonal Banana', 9)

INSERT INTO SONG (id, name, albumID) VALUES (54, 'Beginner''s Luck', 13)
INSERT INTO SONG (id, name, albumID) VALUES (55, 'Greenhouse Heat Death', 13)
INSERT INTO SONG (id, name, albumID) VALUES (56, 'Barefoot Desert', 13)
INSERT INTO SONG (id, name, albumID) VALUES (57, 'Muddy Water', 13)
INSERT INTO SONG (id, name, albumID) VALUES (58, 'Superposition', 13)
INSERT INTO SONG (id, name, albumID) VALUES (59, 'Down the Sink', 13)
INSERT INTO SONG (id, name, albumID) VALUES (60, 'The Great Chain of Being', 13)
INSERT INTO SONG (id, name, albumID) VALUES (61, 'The Last Oasis', 13)
INSERT INTO SONG (id, name, albumID) VALUES (62, 'All Is Known', 13)
INSERT INTO SONG (id, name, albumID) VALUES (63, 'I''m Sleepin'' In', 13)
INSERT INTO SONG (id, name, albumID) VALUES (64, 'The Wheel', 13)

INSERT INTO SONG (id, name, albumID) VALUES (65, 'Elbow', 1)
INSERT INTO SONG (id, name, albumID) VALUES (66, 'Muckraker', 1)
INSERT INTO SONG (id, name, albumID) VALUES (67, 'Nein', 1)
INSERT INTO SONG (id, name, albumID) VALUES (68, '12 Bar Bruise', 1)
INSERT INTO SONG (id, name, albumID) VALUES (69, 'Garage Liddiard', 1)
INSERT INTO SONG (id, name, albumID) VALUES (70, 'Sam Cherry''s Last Shot', 1)
INSERT INTO SONG (id, name, albumID) VALUES (71, 'High Hopes Low', 1)
INSERT INTO SONG (id, name, albumID) VALUES (72, 'Cut Throat Boogie', 1)
INSERT INTO SONG (id, name, albumID) VALUES (73, 'Bloody Ripper', 1)
INSERT INTO SONG (id, name, albumID) VALUES (74, 'Uh Oh, I Called Mum', 1)
INSERT INTO SONG (id, name, albumID) VALUES (75, 'Sea of Trees', 1)
INSERT INTO SONG (id, name, albumID) VALUES (76, 'Footy Footy', 1)

INSERT INTO SONG (id, name, albumID) VALUES (77, 'Eyes Like the Sky', 2)
INSERT INTO SONG (id, name, albumID) VALUES (78, 'Year of Our Lord', 2)
INSERT INTO SONG (id, name, albumID) VALUES (79, 'The Raid', 2)
INSERT INTO SONG (id, name, albumID) VALUES (80, '', 2)